// <auto-generated />
using api.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace api.Migrations.Covalisage
{
    [DbContext(typeof(CovalisageContext))]
    partial class CovalisageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Domain.Annonce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<string>("UserId");

                    b.Property<string>("dateArrivee");

                    b.Property<string>("dateDepart");

                    b.Property<string>("lieuArrivee");

                    b.Property<string>("lieuDepart");

                    b.Property<int>("poidDisponible");

                    b.Property<double>("prixKg");

                    b.Property<string>("titre");

                    b.HasKey("Id");

                    b.ToTable("Annonces");
                });
#pragma warning restore 612, 618
        }
    }
}
