// <auto-generated />
using covalisage.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace covalisage.Migrations
{
    [DbContext(typeof(MyWebApiContext))]
    [Migration("20180408165417_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("covalisage.Domain.Colis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Poid");

                    b.Property<decimal>("Prix");

                    b.Property<int>("UserId");

                    b.Property<string>("note");

                    b.HasKey("Id");

                    b.ToTable("Colis");
                });

            modelBuilder.Entity("covalisage.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ColisId");

                    b.Property<int>("Qte");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.HasIndex("ColisId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("covalisage.Domain.Item", b =>
                {
                    b.HasOne("covalisage.Domain.Colis")
                        .WithMany("listeItems")
                        .HasForeignKey("ColisId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
